pipeline {
    agent {
        kubernetes {
            defaultContainer 'jenkins-worker'
        }
    }
    environment {
        REPOSITORY = "harbor.loremxd/app"
        IMAGE_NAME = "${REPOSITORY}/frontend"
        TRIVY_CACHE_DIR = "/home/jenkins/agent/caches/trivy"
        TAG = "v${BUILD_NUMBER}"
    }
    stages {
        stage('Checkout') {
            steps {
                git url: 'git@github.com:LoremXd/app.git', branch: 'master', credentialsId: 'jenkins-ssh-key'
            }
        }
        stage('Build image') {
            steps {
                container('kaniko') {
                    sh '''
                        /kaniko/executor \
                            --dockerfile frontend/Dockerfile \
                            --destination ${IMAGE_NAME}:${TAG} \
                            --context ${WORKSPACE}/frontend \
                            --cache \
                            --cache-repo ${REPOSITORY}/frontend-cache
                    '''
                }
            }
        }
        stage('Scan images with Trivy') {
            steps {
                container('trivy') {
                    sh '''
                        mkdir -p reports
                        trivy image \
                            --exit-code 0 \
                            --severity CRITICAL,HIGH,MEDIUM \
                            --ignore-unfixed \
                            --format template \
                            --template @${TRIVY_CACHE_DIR}/html.tpl \
                            --cache-dir ${TRIVY_CACHE_DIR} \
                            --output ${WORKSPACE}/reports/trivy-report-frontend.html \
                        ${IMAGE_NAME}:${TAG}
                    '''
                }
            }
        }
        stage('Deploy') {
            steps {
                container('helm') {
                    withKubeConfig([credentialsId: 'jenkins-kubeconfig']) {
                        sh '''
                            HELM_CACHE_HOME=${WORKSPACE}/helm \
                            helm upgrade app-frontend helm/frontend -n app \
                                --wait
                        '''
                    }
                }
            }
        }
    }
    post {
        success {
            script {
                publishHTML([
                    allowMissing: false,
                    alwaysLinkToLastBuild: true,
                    keepAll: true,
                    reportDir: 'reports',
                    reportFiles: 'trivy-report-frontend.html',
                    reportName: 'Trivy Vulnerability Report'
                ])
            }
        }
    }
}
