apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ if .Values.namespace.create }}{{ .Values.namespace.name }}{{ end }}
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: {{ .Values.backend.name }}
