apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: {{ if .Values.namespace.create }}{{ .Values.namespace.name }}{{ end }}
spec:
  claimRef:
    name: postgres-pvc
    namespace: {{ if .Values.namespace.create }}{{ .Values.namespace.name }}{{ end }}
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: "/mnt/app/postgres"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: {{ if .Values.namespace.create }}{{ .Values.namespace.name }}{{ end }}
spec:
  volumeName: postgres-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
